## Lecture 6 Numpy

In [1]:
import numpy as np 

In [2]:
arr1 = np.array([1,2,35,1])
print(arr1)

[ 1  2 35  1]


In [4]:
arr1

array([ 1,  2, 35,  1])

In [3]:
type(arr1)

numpy.ndarray

In [ ]:
np.array([1,2,3.1])

array([1. , 2. , 3.1])

In [6]:
np.array([1,2,3.1], dtype=int)

array([1, 2, 3])

In [15]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
arr2 = np.full((3,4),5)
arr2

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [17]:
dir(arr2)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '_

In [18]:
arr2.ndim

2

In [20]:
arr 

array([1, 2, 3, 5])

In [19]:
arr.shape

(4,)

In [21]:
arr2.shape

(3, 4)

In [22]:
np.array([1,2, 4.5, 7], dtype = float).nbytes

32

In [28]:
np.array([1,2, 4.5, 7], dtype = 'int8').nbytes

4

In [43]:
np.random.seed(0)
x2 = np.random.randint(20, size=(3,4))
x2 

array([[12, 15,  0,  3],
       [ 3,  7,  9, 19],
       [18,  4,  6, 12]], dtype=int32)

In [48]:
# 2-dimension array ~ nested list
x2[0][1]=16
x2 

array([[12, 16,  0,  3],
       [ 3,  7,  9, 19],
       [18,  4,  6, 12]], dtype=int32)

In [49]:
x2[1,3]

np.int32(19)

In [6]:
import numpy as np

In [7]:
np.random.seed(0)
arr3 = np.random.randint(20,size=(2,12))
print(arr3)

[[12 15  0  3  3  7  9 19 18  4  6 12]
 [ 1  6  7 14 17  5 13  8  9 19 16 19]]


In [8]:
arr31 = arr3.reshape((3,8))
print(arr31)
arr31[0,1]=22  

[[12 15  0  3  3  7  9 19]
 [18  4  6 12  1  6  7 14]
 [17  5 13  8  9 19 16 19]]


In [9]:
print(arr3)
print(arr31)

[[12 22  0  3  3  7  9 19 18  4  6 12]
 [ 1  6  7 14 17  5 13  8  9 19 16 19]]
[[12 22  0  3  3  7  9 19]
 [18  4  6 12  1  6  7 14]
 [17  5 13  8  9 19 16 19]]


In [10]:
arr4 = np.arange(1,10)
arr4 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.split(arr4, [2])

[array([1, 2]), array([3, 4, 5, 6, 7, 8, 9])]

In [12]:
np.split(arr4, [2,5])

[array([1, 2]), array([3, 4, 5]), array([6, 7, 8, 9])]

In [13]:
arr31

array([[12, 22,  0,  3,  3,  7,  9, 19],
       [18,  4,  6, 12,  1,  6,  7, 14],
       [17,  5, 13,  8,  9, 19, 16, 19]], dtype=int32)

In [14]:
np.split(arr31,[1], axis= 1)

[array([[12],
        [18],
        [17]], dtype=int32),
 array([[22,  0,  3,  3,  7,  9, 19],
        [ 4,  6, 12,  1,  6,  7, 14],
        [ 5, 13,  8,  9, 19, 16, 19]], dtype=int32)]

In [15]:
np.hsplit(arr31,[1])

[array([[12],
        [18],
        [17]], dtype=int32),
 array([[22,  0,  3,  3,  7,  9, 19],
        [ 4,  6, 12,  1,  6,  7, 14],
        [ 5, 13,  8,  9, 19, 16, 19]], dtype=int32)]

In [16]:
#ufunction
arr5 = list(range(10**6))
arr6 = np.array(arr5)

In [17]:
%timeit sum(arr5)

65.7 ms ± 9.46 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [18]:
%timeit sum(arr6)

102 ms ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [19]:
%timeit np.sum(arr6)

961 μs ± 45.7 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [20]:
np.random.seed(0)
x  = np.random.randint(10, size=(3,4))
x 

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]], dtype=int32)

In [21]:
import my_module as mm 

In [22]:
mm.is_prime(7)

True

In [23]:
#map
f = lambda x: x*2
list(map(f, [2,1,4,6]))

[4, 2, 8, 12]

In [25]:
x.flatten()[np.array(list(map(mm.is_prime, x.flatten())))].sum()

np.int64(35)

In [28]:
arr7 = np.array([[10,40],
                 [30,20]])
print(arr7)
arr7.sort(axis=0)
print(arr7)

[[10 40]
 [30 20]]
[[10 20]
 [30 40]]


In [29]:
arr7 = np.array([[10,40],
                 [30,20]])
print(arr7)
arr7.sort(axis=1)
print(arr7)

[[10 40]
 [30 20]]
[[10 40]
 [20 30]]


In [31]:
arr7 = np.array([[10,40],
                 [30,20]])
print(arr7)
np.sort(arr7,axis=None)

[[10 40]
 [30 20]]


array([10, 20, 30, 40])

In [36]:
a =x.flatten() 
a 

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6], dtype=int32)

In [37]:
np.sort(a)

array([0, 2, 3, 3, 3, 4, 5, 5, 6, 7, 7, 9], dtype=int32)

In [38]:
np.argsort(a)

array([ 1,  8,  3,  2,  6,  9,  0,  7, 11,  4, 10,  5])

In [39]:
a 

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4, 7, 6], dtype=int32)

In [40]:
a[np.argsort(a)]

array([0, 2, 3, 3, 3, 4, 5, 5, 6, 7, 7, 9], dtype=int32)